# Generated by Django 3.1.5 on 2021-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('parentsname', models.CharField(max_length=200)),
                ('medications', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_phonenumber', models.IntegerField(blank=True)),
            ],
        ),
    ]
