# Generated by Django 3.1.5 on 2021-02-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_care', '0002_auto_20210219_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
